// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class SliceableOpaque {
    /** @internal */
    get ffiValue(): pointer;


    get num(): number;

    constructor(i: number);
}