// generated by diplomat-tool
import type { SliceableOpaque } from "./SliceableOpaque"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class SliceableOpaqueHolder {
    /** @internal */
    get ffiValue(): pointer;


    mismatchLtRet(): Array<SliceableOpaque>;

    constructor(sl: SliceableOpaque);
}