// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class SliceableOpaque {
    /** @internal */
    get ffiValue(): pointer;


    get num(): number;

    static optionalOpaqueInout(sl: Array<SliceableOpaque | null>): Array<SliceableOpaque | null>;

    constructor(i: number);
}