[workspace]
resolver = "2"
members = ["bindings", "test"]

[workspace.dependencies]
shared-rust-feature-test-bindings = { path= "bindings" }
diplomat-feature-tests = { path = "../" }
diplomat-runtime = { path="../../runtime"}