[package]
name = "feature_tests_static_rust"
publish = false

[workspace]

[lib]
path = "src/lib.rs"

[dependencies]
diplomat-runtime = "0.12.0"
diplomat_static_rust = { path = "../../../static_rust_macro" }
